#!/usr/bin/env bash
# This script is used to ping 5 times an IP adress and return default string if no argument is passed
if [ ! $1 ]; then
    echo "5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 $1
fi
