#!/usr/bin/env bash
# This script onfigures an Ubuntu server with the below requirements
sed -i 's/^127\.0\.0\.1/# &/' /etc/hosts
{
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
 } >>  /etc/hosts
