#!/usr/bin/env bash
# This script onfigures an Ubuntu server with the below requirements
sed -i 's/^127\.0\.0\.1/# unactive line: &/' /etc/hosts
sed -i 's/^\:\:1/# unactive line: &/' /etc/hosts
{
    echo "# Addind these 2 new lines"
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
 } >>  /etc/hosts
